#!/bin/bash

dir="$1"

MODE=755

echo "Перевожу..."
while read -r line; do
  line2="${line##*/}"
  name="$(/usr/share/rubin/translate_bin "$line2")"
  [ -d "$dir"/"$name" ] && continue
  [ -f "$dir"/"$name" ] && continue
  echo " $line2 => $name"
  install -D -m $MODE /usr/share/rubin/test "$dir"/"$name"
  sed -i "s/\-\-\-/$i/g" "$dir"/"$name"
done
